name: Update Simpsons Data

on: [push]

jobs:
  update_plot:
    name: Update plot with new extreme weather data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script and Update data
        run: |
          jupyter nbconvert --to script simpsons-tv-data-generator.ipynb
          python simpsons-tv-data-generator.py

        # Kaggle credentials as environment variables
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

