name: Update Simpsons Data

on: [push]

jobs:
  update_plot:
    name: Check for simpsons data update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script and Update data
        run: python simpsons-generator.py
        # Kaggle and TMDB credentials as environment variables
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
          TMDB_KEY: ${{ secrets.TMDB_KEY }}
